### ISSUE TITLE
In your example you have the lat and lon values flipped for both Berlin ans Oslo

### ISSUE THREAD

**Issue by ajones** [walling/geo-distance#2]
Also I always get NAN as the result. If I swap lat and lon before passing to your distance function I get an answer but it is very wrong.

**Comment by walling** [comment]
Unfortunately this project is under-maintained. If you care to send a pull request fixing the issue, I am happy to merge it.

**Comment by ajones** [comment]
@walling no problem. I will get on this.

**Comment by thesequelgroup** [comment]
I can't believe this plugin was downloaded 64,301 times last month and the Lat/Lng values are still in the wrong order.

**Comment by bigman73** [comment]
@ajones please merge the PR

**Comment by walling** [comment]
This is fixed in [v0.2.0](https://www.npmjs.com/package/geo-distance/v/0.2.0). Please upgrade and test. Sorry for the immense waiting time.

**Comment by SergeySkyline** [comment]
unrelated note, i think you should update the example to Paris & Berlin, like in that pretty famous song
https://www.youtube.com/watch?v=THt5u-i2d9k
