### ISSUE TITLE
Seems there is no way to get numeric distance in, say, metres.

### ISSUE THREAD

**Issue by remster** [walling/geo-distance#5]
Just human readable.

**Comment by walling** [comment]
@remster Thanks for your comment. Personally, I would switch to [@turf/distance](https://www.npmjs.com/package/@turf/distance) npm for that purpose.

**Comment by walling** [comment]
@remster If you like to improve the library, please feel free to send a PR adding a function to get the numeric distance. Otherwise, I'm closing the issue for now.
